name: Publish
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.148.2'
          extended: true
      - name: Home
        run: git submodule add -f https://github.com/rosano/home.git themes/home
      - name: Unconfig
        run: git submodule add -f https://github.com/rosano/home-unconfig.git themes/home-unconfig
      - name: Build
        run: hugo
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
